### PR TITLE
fix(useDidUnmount): call effect with updated dependencies

### LINKED ISSUE #8: Bug on `useDidUnmount`
I had some issues while trying to use the `useDidUnmount` with a function that gets updated over the time.

My hook is something like the following:

```tsx

const useCounter = (handleCounterSave: (countValue: number) => void) => {
  const [count, setCounter] = useState(0);

  const increment = useCallback(() => {
    setCounter(count + 1);
  }, [count]);
  const decrement = useCallback(() => {
    setCounter(count + 1);
  }, [count]);

  const saveCounter = useCallback(() => {
    handleCounterSave(count);
  }, [count, handleCounterSave]);

  useDidUnmount(saveCounter);

  return {
    increment,
    decrement,
    count,
  };
};
```

After calling `increment` a few times (thrice for example) and unmounting the view, the `handleCounterSave` is called with `0` as the `countValue` when it should be `3`.

I'm using the `0.2.0` version.

### PR DESCRIPTION
**Pull request by fjcaetano**
Now, when the effect is called, it will have updated dependencies, if they have been passed.

fix #8

### CODE REVIEW

File: src/__tests__/useDidUnmount.ts [hunk 1]
```diff
@@ -52,10 +54,38 @@ it('runs an async funciton', async () => {
...
+
+it('does not update the effect when the dependencies have not been updated', () => {
+  const secondCleanup = jest.fn();
+  const { unmount, rerender } = renderHook(hook, {
+    initialProps: { func: cleanup, deps: [cleanup] },
+  });
+
+  // sending a new cleanup func, but keeping the same dependencies
+  rerender({ func: secondCleanup, deps: [cleanup] });
+  unmount();
```
Comment (uqmessias) [inline src/__tests__/useDidUnmount.ts:87]: What happens if we call `unmount` one more time here? Does it make sense for us to add a test for this scenario?

File: src/index.tsx [hunk 2]
```diff
@@ -134,15 +134,33 @@ export const useDidMount = (
...
-      effect();
+      unmounting.current = true;
     },
     [],
   );
+
+  useEffect(
+    () => () => {
+      if (unmounting.current) {
+        effect();
```
Comment (uqmessias) [inline src/index.tsx:159]: In order to avoid multiple calls to `effect`, does it make sense for us to update `unmount.current` to `false` here again?

File: src/index.tsx [hunk 3]
```diff
@@ -134,15 +134,33 @@ export const useDidMount = (
...
-export const useDidUnmount = (effect: () => void | Promise<void>) => {
+export const useDidUnmount = <Dependencies extends readonly any[]>(
+  effect: () => void | Promise<void>,
+  dependencies?: Dependencies,
+) => {
+  const unmounting = useRef(false);
   useEffect(
     () => () => {
-      effect();
+      unmounting.current = true;
```
Comment (uqmessias) [inline src/index.tsx:151]: 💯

**Review by uqmessias — APPROVED** [review]
LGTM

File: src/__tests__/useDidUnmount.ts (hunk 1 above)
Comment (fjcaetano) [reply src/__tests__/useDidUnmount.ts:87]: Multiple calls to `unmount` is already being tested. There's no need to check for it here too.

File: src/index.tsx (hunk 2 above)
Comment (fjcaetano) [reply src/index.tsx:159]: Do you have an example of `effect` being called multiple times? I don't see how that would be possible since `unmounting.current` is only set to `true` when the component is being unmounted. Therefore, `useEffect` would have to be calling the cleanup function twice in order for the `effect` to be called again.

Comment (uqmessias) [reply src/index.tsx:159]: It makes sense, I just thought about this `useEffect` being called several times because of the change on its dependencies, but `unmounting.current` only will be `true` when the component really is unmounted.
