### PR TITLE
fix(useLazyRef): remove extra call to useRef

### LINKED ISSUE #6: Bug on `useLazyRef`
I was struggling with some tests failing on my codebase and after some minutes, I realized it was related to the use of [`useLazyRef`](https://github.com/fjcaetano/react-hook-utilities/blob/master/src/index.tsx#L157).

I locally updated the lib code and it worked well.

The problem is regarding [one of the rules of React Hooks](https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level) that this method is breaking:

> ## Only Call Hooks at the Top Level 
> Don’t call Hooks inside loops, **conditions**, or nested functions. ...
> — https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level

### PR DESCRIPTION
**Pull request by uqmessias**
Remove an extra call to `useRef` that violates one of the rules of
React Hooks: **call a hook unconditionally**.

Fix #6

### CODE REVIEW

File: src/index.tsx [hunk 1]
```diff
@@ -153,6 +153,11 @@ export const useDidUnmount = (effect: () => void | Promise<void>) => {
 export const useLazyRef = <T extends any>(
   factory: () => T,
 ): MutableRefObject<T> => {
-  const initialValue = useRef<MutableRefObject<T> | undefined>(undefined);
-  return initialValue.current || (initialValue.current = useRef(factory()));
+  const ref = useRef<T | undefined>(undefined);
+
+  if (ref.current === void 0 || ref.current === null) {
```
Comment (fjcaetano) [inline src/index.tsx:158]: 💯

**Review by fjcaetano — APPROVED** [review]
LGTM
